package conversor.vista;

import javax.swing.JOptionPane;

public class VistaTemperatura extends javax.swing.JFrame {

    VistaConversores vc = new VistaConversores();

    public VistaTemperatura() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLConvertir = new javax.swing.JLabel();
        jConvertirA = new javax.swing.JComboBox<>();
        jLConvertir1 = new javax.swing.JLabel();
        jConvertir = new javax.swing.JComboBox<>();
        jLConvertir2 = new javax.swing.JLabel();
        jBtnAceptar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jTCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(490, 280));

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));
        jPanel2.setAlignmentX(0.5F);
        jPanel2.setAlignmentY(0.5F);
        jPanel2.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(534, 341));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(534, 341));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONVERSOR DE TEMPERATURA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 290, 30));

        jLConvertir.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLConvertir.setForeground(new java.awt.Color(255, 255, 255));
        jLConvertir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLConvertir.setText("a");
        jPanel2.add(jLConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, 30));

        jConvertirA.setBackground(new java.awt.Color(51, 204, 255));
        jConvertirA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Faharenheit", "Kelvin", "Rankine", "Réaumur" }));
        jConvertirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConvertirAActionPerformed(evt);
            }
        });
        jPanel2.add(jConvertirA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, -1));

        jLConvertir1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLConvertir1.setForeground(new java.awt.Color(255, 255, 255));
        jLConvertir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLConvertir1.setText("Cantidad");
        jPanel2.add(jLConvertir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, 30));

        jConvertir.setBackground(new java.awt.Color(51, 0, 153));
        jConvertir.setForeground(new java.awt.Color(255, 255, 255));
        jConvertir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Faharenheit", "Kelvin", "Rankine", "Réaumur" }));
        jConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jConvertir.setName(""); // NOI18N
        jConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConvertirActionPerformed(evt);
            }
        });
        jPanel2.add(jConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 130, -1));

        jLConvertir2.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLConvertir2.setForeground(new java.awt.Color(255, 255, 255));
        jLConvertir2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLConvertir2.setText("Convertir");
        jPanel2.add(jLConvertir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 30));

        jBtnAceptar.setBackground(new java.awt.Color(255, 255, 0));
        jBtnAceptar.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jBtnAceptar.setText("ACEPTAR");
        jBtnAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 130, 50));

        jBtnCancelar.setBackground(new java.awt.Color(255, 255, 0));
        jBtnCancelar.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jBtnCancelar.setText("CANCELAR");
        jBtnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 130, 50));

        jTCantidad.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jPanel2.add(jTCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConvertirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConvertirAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConvertirAActionPerformed

    private void jConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConvertirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConvertirActionPerformed

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
        // TODO add your handling code here:
        if (jTCantidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escriba la cantidad que desea cambiar");
        } else {
            if (jConvertir.getSelectedItem().equals("Celsius") && jConvertirA.getSelectedItem().equals("Faharenheit")) {
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText()) * 9 / 5))+32;
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °C " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °F" );
            }else if(jConvertir.getSelectedItem().equals("Celsius") && jConvertirA.getSelectedItem().equals("Kelvin")){
                double calculoConvesion = (Double.parseDouble(jTCantidad.getText())+273.15);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °C " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °K" );
            }else if(jConvertir.getSelectedItem().equals("Celsius") && jConvertirA.getSelectedItem().equals("Rankine")){
                double calculoConvesion = (Double.parseDouble(jTCantidad.getText())+273.15)*9/5;
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °C " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °R" );
            }else if(jConvertir.getSelectedItem().equals("Celsius") && jConvertirA.getSelectedItem().equals("Réaumur")){
                double calculoConvesion = (Double.parseDouble(jTCantidad.getText())+273.15)*9/5;
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °C " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °Re" );
            }else if(jConvertir.getSelectedItem().equals("Kelvin") && jConvertirA.getSelectedItem().equals("Celsius")){
                double calculoConvesion = (Double.parseDouble(jTCantidad.getText())-273.15);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °K " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °C" );
            }else if(jConvertir.getSelectedItem().equals("Kelvin") && jConvertirA.getSelectedItem().equals("Faharenheit")){
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText())-273.15)*9/5)+32;
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °K " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °F" );
            }else if(jConvertir.getSelectedItem().equals("Kelvin") && jConvertirA.getSelectedItem().equals("Rankine")){
                double calculoConvesion = (Double.parseDouble(jTCantidad.getText())*9/5);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °K " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °R" );
            }else if(jConvertir.getSelectedItem().equals("Kelvin") && jConvertirA.getSelectedItem().equals("Réaumur")){
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText())-273.15)*4/5);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °K " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °Ra" );
            }else if(jConvertir.getSelectedItem().equals("Faharenheit") && jConvertirA.getSelectedItem().equals("Celsius")){
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText())-32)* 5/ 9);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °F " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °C" );
            }else if(jConvertir.getSelectedItem().equals("Faharenheit") && jConvertirA.getSelectedItem().equals("Kelvin")){
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText())-32)* 5/ 9)+273.15;
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °F " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °K" );
            }else if(jConvertir.getSelectedItem().equals("Faharenheit") && jConvertirA.getSelectedItem().equals("Rankine")){
                double calculoConvesion = (Double.parseDouble(jTCantidad.getText())+459.67);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °F " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °R" );
            }else if(jConvertir.getSelectedItem().equals("Faharenheit") && jConvertirA.getSelectedItem().equals("Réaumur")){
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText())-32)* 4/ 9);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °F " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °Ra" );
            }else if(jConvertir.getSelectedItem().equals("Rankine") && jConvertirA.getSelectedItem().equals("Celsius")){
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText())-491.67)*5/9);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °R " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °C" );
            }else if(jConvertir.getSelectedItem().equals("Rankine") && jConvertirA.getSelectedItem().equals("Faharenheit")){
                double calculoConvesion = (Double.parseDouble(jTCantidad.getText())-459.67);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °R " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °F" );
            }else if(jConvertir.getSelectedItem().equals("Rankine") && jConvertirA.getSelectedItem().equals("Kelvin")){
                double calculoConvesion = (Double.parseDouble(jTCantidad.getText())*5/9);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °R " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °K" );
            }else if(jConvertir.getSelectedItem().equals("Rankine") && jConvertirA.getSelectedItem().equals("Réaumur")){
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText())-491.67)*4/9);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °R " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °Ra" );
            }else if(jConvertir.getSelectedItem().equals("Réaumur") && jConvertirA.getSelectedItem().equals("Celsius")){
                double calculoConvesion = (Double.parseDouble(jTCantidad.getText())*5/4);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °Ra " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °C" );
            }else if(jConvertir.getSelectedItem().equals("Réaumur") && jConvertirA.getSelectedItem().equals("Faharenheit")){
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText())*9/4)+32);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °Ra " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °F" );
            }else if(jConvertir.getSelectedItem().equals("Réaumur") && jConvertirA.getSelectedItem().equals("Kelvin")){
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText())*5/4)+273.15);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °Ra " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °K" );
            }else if(jConvertir.getSelectedItem().equals("Réaumur") && jConvertirA.getSelectedItem().equals("Rankine")){
                double calculoConvesion = ((Double.parseDouble(jTCantidad.getText())*9/4)+491.67);
                JOptionPane.showMessageDialog(null, jTCantidad.getText() + " °Ra " +  " equivale a : " + String.format("%.6f", calculoConvesion) + " °R" );
            }
        }
        jTCantidad.setText("");
        jTCantidad.grabFocus();
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
        vc.setVisible(true);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JComboBox<String> jConvertir;
    private javax.swing.JComboBox<String> jConvertirA;
    private javax.swing.JLabel jLConvertir;
    private javax.swing.JLabel jLConvertir1;
    private javax.swing.JLabel jLConvertir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTCantidad;
    // End of variables declaration//GEN-END:variables
}
